# Generated by Django 4.2.16 on 2024-10-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_premiummembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiummembership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
